### ISSUE TITLE
How to detect protection key?

### ISSUE THREAD

**Issue by computer990784** [Sinflower/UberWolf#10]
First of all, sorry if this is a dumb question. I know nothing about programmings and stuff.
There's a game made with WolfRPG Pro that I'd want to decrypt but when I try to decrypt it with this tool, it says this:
![Uberwolf v0 3 1 2024_10_25 16_13_52](https://github.com/user-attachments/assets/8c31dd01-ab95-4615-9f84-024a6cb402da)

And then an empty Data file gets generated.

Do that means it's impossible to decrypt this game? What should I do?

**Comment by Sinflower** [comment]
Hmm, that's strange. Can you give me the name of the game so I can take a look and try to fix the problem?

**Comment by computer990784** [comment]
Umm... don't know if it's ok, since it's a free trial, here's the link:
ttps://ci-en.dlsite.com/creator/813/article/1265100.

Thank you  m(_ _)m

**Comment by Sinflower** [comment]
The trial version you linked decrypts just fine for me; you might need to wait a bit for the decryption to finish (~1 minute). The message regarding the protection key can be ignored because although the game is made with WolfPro, the game data is not protected (probably because it is a trial version).

If nothing is extracted even after waiting several minutes, please let me know, and I will look into it.

**Comment by computer990784** [comment]
Sadly, it still did not work for me... The program just shuts off after like 5 seconds I pressed progress button, leaving an empty data file.
I recorded the thing, maybe the video can help you figure out what is happening:
https://imgur.com/a/HHHpGIM

Thank you!

**Comment by Sinflower** [comment]
Very strange, the application closing itself implies that it crashes somewhere during the extraction process. I will try to look into it. 
Could you try to unpack [this game](https://gofile.io/d/nMZz7c)? It's just the example game shipped with the latest version of the free Wolf RPG Editor. It would be interesting if this also crashes the application.

In the meantime, I took the liberty of uploading the unpacked data of the trial version for you [here](https://gofile.io/d/jY8Ml2).

**Comment by computer990784** [comment]
I honestly could not thank you for all that you are doing for me...

As for the test game, I was able to decrypt it with no problem. All the decrypted data files appeared normally in the generated folder.
Thank you so much for uploading th unpacked data... I hope you're able to find out what's wrong for my case, too. Again, thank you so much!!!

**Comment by Sinflower** [comment]
I have been rather busy lately, and after fixing the problem, I forgot to create a new release. The new version 0.4.1 should no longer crash when trying to unpack this game or any game with a single large file.
