### ISSUE TITLE
Request support for .dat and .mps

### ISSUE THREAD

**Issue by as176590811** [Sinflower/UberWolf#2]
Request support for decryption, modification, encryption, etc., of .dat and .mps format files.

**Comment by Sinflower** [comment]
I recommend using the Wolf RPG Editor or Translator++ to modify the game files.

**Comment by dazedanon** [comment]
I second this. If you use a 3rd party tool to MTL files, you aren't able to use Wolf RPG Editor or T++ (Unless you convert to csv which often fails) to actually edit those files. So it would be nice if we could get a decrypted version of .dat and .mps files that can be repacked into the game if possible. 

I also find it easier to work with the files that way versus using Wolf RPG Engine and T++.

**Comment by Sinflower** [comment]
OK, I will look at this and get back to you once I am done.

**Comment by Sinflower** [comment]
Done, please check out:
https://github.com/Sinflower/WolfTL

**Comment by as176590811** [comment]
> Done, please check out: https://github.com/Sinflower/WolfTL

Thank you very much to the creator for making this tool; it's a lot of hard work. Additionally, for better usage, it's recommended to first convert the data to utf8 using WOLF_RPG_Editor3 before decrypting and encrypting for optimal results.
