### ISSUE TITLE
[Feature request]: packing unpacked files back to .wolf

### ISSUE THREAD

**Issue by suphamster** [Sinflower/UberWolf#4]
Not super useful feature since game engine reads unpacked files fine but could be useful anyway coz some games have about 30k files after as wolf files extraction.
_Btw in readme about command line maybe useful to add info about possibility of usage such code too (and not only drag'n'drop coz it's not pure cmd):_
`UberWolfCli.exe "C:\game_name\Data"`
or individual file:
`UberWolfCli.exe "C:\game_name\Data\BasicData.wolf"`

**Comment by Sinflower** [comment]
I will look into it, but in general, the files can simply be repacked using the editor, so it might be obsolete.
I will update the readme accordingly.

**Comment by suphamster** [comment]
Hi, I see that you added packing that is good news but looks like GUI version only yet that is sad. Can you please add packing to CLI version too? Also I have a question what to do with "unprotected" folder that created by your tool after unpacking? Can I just delete that folder?

**Comment by Sinflower** [comment]
> Can you please add packing to CLI version too?

Yes, I will add packing to the CLI as well; I just forgot about it when I made the GUI update.

> Also I have a question what to do with "unprotected" folder that created by your tool after unpacking? Can I just delete that folder?

The "unprotected" folder is created for Pro games (< 3.31) and contains unencrypted versions of certain BasicData files so that the Pro project can also be opened using the non-Pro editor. It's more of a special use-case thing and can generally be ignored/deleted.

**Comment by Brothers3398** [comment]
wolfrpg add CLI packing in 3.385
[patchnote3.385.txt](https://github.com/user-attachments/files/16975403/patchnote3.385.txt)

i tyring test using with locale Emulator it work well

**Comment by Sinflower** [comment]
I was rather busy ... and forgot to create the new release, but the command line application should now be able to repack wolf files. Though I would probably recommend using the editor :-),

**Comment by Brothers3398** [comment]
> I was rather busy ... and forgot to create the new release, but the command line application should now be able to repack wolf files. Though I would probably recommend using the editor :-),

[WOLF_RPG_Editor_3.396_Pro_2024_0913_mini_9MB.zip](https://github.com/user-attachments/files/18181512/WOLF_RPG_Editor_3.396_Pro_2024_0913_mini_9MB.zip)

here WOLF RPG PRO lastest ver 3.396 :)
when you check it plz delete this message it maybe illegal
