### ISSUE TITLE
WolfRPG added new encryption

### ISSUE THREAD

**Issue by Brothers3398** [Sinflower/UberWolf#5]
sorry my english is bad

WolfRPG added new encryption ver Ver3.310
so i testing that using editor 3.334(last released version) can't unpacking .wolf
can you support for that encryption?

**Comment by Sinflower** [comment]
I have added experimental support for the new encryption.
As it is currently primarily adopted IDA code, I have not created a new release.
Once the code has been cleaned up and properly tested, it will be included in the next release.

**Comment by Brothers3398** [comment]
I see i hope it work well
thx to supprot
