### ISSUE TITLE
How to use the program without programming knowledge

### ISSUE THREAD

**Issue by Consilie** [Sinflower/UberWolf#6]
Hello. First of all, I want to thank the creator of this program, it is, in fact, the only working scheme for decrypting files of this format. But unfortunately, I can't figure out how to run it. As a person with no programming experience, I don't quite understand what to do. There is no EXE file, when entered via the command line it outputs: "UberWolfCli.exe " is not an internal or external command, executable program, or batch file. Does it need to be run through Visual Studio? I would like step-by-step instructions for such underdeveloped people like me. Thank for your understanding.

**Comment by Sinflower** [comment]
Hi,
in general, I would recommend using the Graphical User Interface (GUI) version of the tool. You can find it on the release page ([here](https://github.com/Sinflower/UberWolf/releases)) listed as `UberWolf.exe`. Using the GUI should be rather straightforward; just drag and drop either a `.wolf` file or the `game.exe` onto the marked area, and it will directly extract it (for `.wolf` files) or start extracting every file once you press `Process`.

Now for your actual question about how to use the command-line interface (CLI) version `UberWolfCli.exe`. After downloading the exe, there are two ways to use it.
 - Drag and drop:
    You can simply drag and drop either the Game.exe, the data folder, or several .wolf files onto the exe, and it will automatically process the files accordingly.
 - From the command line:
    Open a command line, e.g., `cmd` and navigate to the folder containing `UberWolfCli.exe`, using the `cd` command, e.g., `cd "C:\Users\USERNAME\Downloads"`. You can press the tab key to auto-complete names and cycle through all possible directory and file names, e.g., if you wrote `cd c:\Users`, pressing tab will cycle through all folders within `c:\Users`. Once you have switched into the folder containing `UberWolfCli.exe` you can use it as described in the main README, e.g., `UberWolfCli.exe "D:\Games\TestGame\Game.exe"`.
   NOTE: If you are not using `cmd` but the `Powershell` or `Windows Terminal`, you need to run the exe as follows: `.\UberWolfCli.exe`.

I hope this answers your questions. If not, feel free to ask additional questions.

**Comment by Consilie** [comment]
> Hi, in general, I would recommend using the Graphical User Interface (GUI) version of the tool. You can find it on the release page ([here](https://github.com/Sinflower/UberWolf/releases)) listed as `UberWolf.exe`. Using the GUI should be rather straightforward; just drag and drop either a `.wolf` file or the `game.exe` onto the marked area, and it will directly extract it (for `.wolf` files) or start extracting every file once you press `Process`.
> 
> Now for your actual question about how to use the command-line interface (CLI) version `UberWolfCli.exe`. After downloading the exe, there are two ways to use it.
> 
>     * Drag and drop:
>       You can simply drag and drop either the Game.exe, the data folder, or several .wolf files onto the exe, and it will automatically process the files accordingly.
> 
>     * From the command line:
>       Open a command line, e.g., `cmd` and navigate to the folder containing `UberWolfCli.exe`, using the `cd` command, e.g., `cd "C:\Users\USERNAME\Downloads"`. You can press the tab key to auto-complete names and cycle through all possible directory and file names, e.g., if you wrote `cd c:\Users`, pressing tab will cycle through all folders within `c:\Users`. Once you have switched into the folder containing `UberWolfCli.exe` you can use it as described in the main README, e.g., `UberWolfCli.exe "D:\Games\TestGame\Game.exe"`.
>       NOTE: If you are not using `cmd` but the `Powershell` or `Windows Terminal`, you need to run the exe as follows: `.\UberWolfCli.exe`.
> 
> 
> I hope this answers your questions. If not, feel free to ask additional questions.

Thank you, you helped me a lot!
