### ISSUE TITLE
Protection key not found

### ISSUE THREAD

**Issue by Aiden1222** [Sinflower/UberWolf#7]
I'm having trouble decrypting a game released 5 days ago. When I run uberwolf and select the gamepro.exe file, it keeps saying "searching for protection key", "key found", "failed to extract looking for new key" over and over again. I thought it might take some time but I've had uberwolf running for 2 days straight and still getting the same results..

**Comment by Sinflower** [comment]
Oh, that's strange. It should not dead-loop there and should stop after the first fail. I will look into it.
But onwards to the actual problem, the game might be using the latest version with a more advanced decryption process. Could you give me the name of the game so I can take a look?

**Comment by Aiden1222** [comment]
Thanks so much for the quick response! It's called DispelSuccubus2, you can find it on DLSite

**Comment by Sinflower** [comment]
As expected, it uses the Pro version of the new protection system.
I am still working on a full integration of all required algorithms right now, but it might take a bit more time.
However, it is already possible to unpack specific games, so I attached a modified version of UberWolf that should allow you to unpack the game in question, but due to the modifications made, most likely only that one.
Should you have any problems, please let me know. You will get a message that the protection key cannot be found, as it is currently not implemented.
[UberWolf_DispelSuccubus2.zip](https://github.com/user-attachments/files/15687571/UberWolf_DispelSuccubus2.zip)

**Comment by Aiden1222** [comment]
Thank you so much! Yeah it must be hard keeping up with the protection updates but you're doing an awesome job! Most people who are getting paid for these services are no where near as active as you are. Is there any way I can support you?

**Comment by Aiden1222** [comment]
Also is there anyway for me to find the protection key for this game? I need to have it to access the game via wolf rpg editor 3 pro

**Comment by Sinflower** [comment]
> Also is there anyway for me to find the protection key for this game? I need to have it to access the game via wolf rpg editor 3 pro

As I currently don't have access to the latest version of the Pro editor I cannot look into the new protection key algorithm.

**Comment by Brothers3398** [comment]
> > Also is there anyway for me to find the protection key for this game? I need to have it to access the game via wolf rpg editor 3 pro
> 
> As I currently don't have access to the latest version of the Pro editor I cannot look into the new protection key algorithm.

i can share wolf rpg PRO editor 3.3x if you need tell me

**Comment by Sinflower** [comment]
> > > Also is there anyway for me to find the protection key for this game? I need to have it to access the game via wolf rpg editor 3 pro
> > 
> > 
> > As I currently don't have access to the latest version of the Pro editor I cannot look into the new protection key algorithm.
> 
> i can share wolf rpg PRO editor 3.3x if you need tell me

If you are willing to do that, that would be great.

**Comment by Brothers3398** [comment]
> > > > Also is there anyway for me to find the protection key for this game? I need to have it to access the game via wolf rpg editor 3 pro
> > > 
> > > 
> > > As I currently don't have access to the latest version of the Pro editor I cannot look into the new protection key algorithm.
> > 
> > 
> > i can share wolf rpg PRO editor 3.3x if you need tell me
> 
> If you are willing to do that, that would be great.

[WOLF_RPG_Editor_3.341_Pro_2024_0606_mini_9MB.zip](https://github.com/user-attachments/files/15749533/WOLF_RPG_Editor_3.341_Pro_2024_0606_mini_9MB.zip)

here.
i thnk sharing is considered illegal If you check it out, please take it and delete my post

**Comment by Sinflower** [comment]
> Also is there anyway for me to find the protection key for this game? I need to have it to access the game via wolf rpg editor 3 pro

The key you are looking for is `zinc`
