### ISSUE TITLE
uberwolf 0.3 can't decrypet protect

### ISSUE THREAD

**Issue by Brothers3398** [Sinflower/UberWolf#8]
sorry my english is not good
I tested the uberwolf 0.3 version, but it doesn't seem to be working well

wolfrpg ver 3.341

editor setting
![image](https://github.com/Sinflower/UberWolf/assets/119965811/eace1114-d89f-4965-9476-6f5f4019f6a7)

packing
![image](https://github.com/Sinflower/UberWolf/assets/119965811/92ee7aef-3620-410d-a66b-1ddc85040194)
stucked :(
![image](https://github.com/Sinflower/UberWolf/assets/119965811/1d1af43c-d99c-4335-bc7d-24fca2fcf2fd)
and file only show decrypt_temp file

also i try test non-protection key 3.31 .wolf decrypt when trying blank .wolf file
uberwolf 0.3 closed and stop decrypt

![image](https://github.com/Sinflower/UberWolf/assets/119965811/f2c254c8-fe64-4d97-9c69-0ceecf2aef81)
that's not the case at 0.2
![image](https://github.com/Sinflower/UberWolf/assets/119965811/8ca1c132-884e-4d44-8bba-918c67023f0e)
but that's great. thank you for make this program

and here uberwolf japanese localization use machine translation
[jp.json](https://github.com/user-attachments/files/15860080/jp.json)

**Comment by Sinflower** [comment]
Hi,
thank you for the feedback.
I am able to reproduce your reported problems and will look into them.
The first problem does not occur if you select the `Overwrite existing extracted data` option from the `Options` menu.

**Comment by Brothers3398** [comment]
> The first problem does not occur if you select the `Overwrite existing extracted data` option from the `Options` menu.

Ah i mean it decrypt failed and only show decrypt_temp
File And sometime uberwolf-data.json(not sure filename is right) file left

Maybe my English and screenshots were misrepresented due to insufficient information

**Comment by Sinflower** [comment]
> Ah i mean it decrypt failed and only show decrypt_temp File And sometime uberwolf-data.json(not sure filename is right) file left

Indeed, I was able to reproduce that behavior, but when I enabled the Overwrite option so that it also extracts BasicData and BattleEffects, which were skipped in your screenshot, the extraction of all files worked. That being said, I will look into the actual problem and fix it as soon as possible.

**Comment by Sinflower** [comment]
Could you give this version a try and tell me if it fixes all the problems you have encountered?
[UberWolf.zip](https://github.com/user-attachments/files/15860504/UberWolf.zip)

**Comment by Brothers3398** [comment]
> Could you give this version a try and tell me if it fixes all the problems you have encountered? [UberWolf.zip](https://github.com/user-attachments/files/15860504/UberWolf.zip)
![image](https://github.com/Sinflower/UberWolf/assets/119965811/7e6890e3-af5e-4ee2-a922-f9dbcad1fc4a)

It works well 
great

and i trying korean localization use machine translation
[ko.json](https://github.com/user-attachments/files/15862080/ko.json)
