### ISSUE TITLE
can unpack .mps?

### ISSUE THREAD

**Issue by Brothers3398** [Sinflower/UberWolf#9]
they doing compressing the mps file after 3.330 patch
So the mps data extractable tools I used before do not work
I don't know much about the compression method, but is it possible to change it to the previous version?

here is patchnote
Ver3.330　2024/04/29
●【マップファイル】マップファイル(.mps)にデータ圧縮を行うようにしました。
　　　　　　似たような空間や建物が多い場合、あるいは広いマップの場合、
　　　　　　.mpsファイルサイズの大幅な削減が期待できます。
　　　→【例】3000x3000のマップを作り、何かマップチップを数マス書き込んで保存すると
　　　　　　従来「100MB以上」のファイルになるところが「400KB程度」になります
　　　　　　（ファイルサイズが約1/250に！)
　　　　　　そこまで行かないケースでも、サンプルゲームのSampleMapA.mpsが
　　　　　　従来52KBだったのが22KBにまで圧縮されることを確認しています。
　　　→【外部ツールを作られている方向けのヒント】
　　　　　Ver3.330で保存した.mpsファイルの26～29バイト目に[解凍後のバイト数]が、
　　　　　30～33バイト目に[圧縮後のバイト数]がint型(4バイト)で格納されており、
　　　　　34バイト目以降の[圧縮後のバイト数]の範囲が
　　　　　LZ4圧縮（ https://github.com/lz4/lz4 のLZ4_compress_default関数）
　　　　　された部分です。
　　　　　非プロテクト版であれば、LZ4の解凍処理（LZ4_decompress_safe関数）を
　　　　　行うことでほぼVer3.32以前と同様のデータフォーマットになるはずです。

**Comment by Sinflower** [comment]
Hi,
here is a simple converter that turns the new mps files back into the old format.
Just drag and drop all mps files onto the exe, and it should create a folder called `converted` containing the files in the old format.
All files not converted by the tool are still in the old format, just in case you wonder why not all files are in the folder.

I will probably create a proper project for this tool at some point.

[MpsConv.zip](https://github.com/user-attachments/files/16448312/MpsConv.zip)

**Comment by Brothers3398** [comment]
> Hi, here is a simple converter that turns the new mps files back into the old format. Just drag and drop all mps files onto the exe, and it should create a folder called `converted` containing the files in the old format. All files not converted by the tool are still in the old format, just in case you wonder why not all files are in the folder.
> 
> I will probably create a proper project for this tool at some point.
> 
> [MpsConv.zip](https://github.com/user-attachments/files/16448312/MpsConv.zip)

thank you, the MPS unpacks seem to be working well(see 2nd picture it same befor 3.28x mps data)
but one more problem i found it
basicdata folder's data format changed after 3.34x(i forget that sorry)
as same extractable tools not work
(in fact, it can be extracted basicdata, but even if the wolfrpg tool does not work properly or the editor runs,
game.exe shuts down or errors immediately after inject data)

can it get these back to the old version like the MPS?


![image](https://github.com/user-attachments/assets/dc5a9762-2f9b-4eb9-9cf2-5d3c3c92c597)


![image](https://github.com/user-attachments/assets/73b53f31-1f25-4471-a97e-5c18f2999583)

**Comment by Sinflower** [comment]
If you want to do a full "revert" of the project I would recommend using [WolfTL](https://github.com/Sinflower/WolfTL). Simply create a patch, e.g., using
`WolfTL.exe Data Patch create`
and then perform in-place patching
`WolfTL.exe Data Patch patch_ip`
this will transform all relevant dat, project, and mps files into their uncompressed and unprotected versions.

A few notes here: TileSetData.dat and Game.dat will not be converted. TileSetData.dat is not touched because it contains no relevant data (at least for the use case of WolfTL), and touching Game.dat tends to break stuff.

If you have any questions or problems, feel free to ask, either here or in the WolfTL issues.

**Comment by Brothers3398** [comment]
thank you for your help
so i was going to test it

> If you want to do a full "revert" of the project I would recommend using [WolfTL](https://github.com/Sinflower/WolfTL). Simply create a patch, e.g., using `WolfTL.exe Data Patch create` and then perform in-place patching `WolfTL.exe Data Patch patch_ip` this will transform all relevant dat, project, and mps files into their uncompressed and unprotected versions.

i serch to test trial game befor 3.3x wolfrpg and i found
寝取られやすい後輩と主無き地/dlsite(RJ01174848)-wolfrpg ver 2.24

1.convert data SHIFT-JIS to UTF
-WOLFRPG supprot this(using 3.282/3.343/3.370)
-Run ok editor is ok

2.revert project

-run
The mps file is processed differently from 3.282 to 3.34x and 2.24 to conversion
If it go from 3.282 to 3.34 right away, it will try to back up, but the mps file not changed
-Run ok editor ok data not identical 3.282 data
-revert project each
-basicdata same/map data diff(but it same 3.282)
-run ok editor ok

i think it's probably okay
i will try patch with this. thank you
